SENSE_EDGES = "static/sense_edges.csv"
LEMMA_SENSE_EDGES = "static/lemma_sense_edges.csv"
TEXT_SENSES = "static/text_senses.json"
CARDWORDS = "static/cardwords.txt"
DICTIONARY = "static/dictionary.json"
LABELS_DIR = "labels"
TEXT_LABELS_DIR = "text_labels"